2022-04-21 15:41:55,962 INFO    MainThread:18404 [wandb_setup.py:_flush():75] Loading settings from C:\Users\alexa\.config\wandb\settings
2022-04-21 15:41:55,962 INFO    MainThread:18404 [wandb_setup.py:_flush():75] Loading settings from C:\Users\alexa\Documents\VT Work\2021-2022 Junior Year\2022 Spring\ECE 4424 Machine Learning\Project\yolov5\wandb\settings
2022-04-21 15:41:55,962 INFO    MainThread:18404 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-04-21 15:41:55,962 INFO    MainThread:18404 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': 'train.py', 'program': 'C:\\Users\\alexa\\Documents\\VT Work\\2021-2022 Junior Year\\2022 Spring\\ECE 4424 Machine Learning\\Project\\yolov5\\train.py'}
2022-04-21 15:41:55,962 INFO    MainThread:18404 [wandb_setup.py:_flush():75] Applying login settings: {'login_timeout': 30}
2022-04-21 15:41:55,962 INFO    MainThread:18404 [wandb_init.py:_log_setup():438] Logging user logs to C:\Users\alexa\Documents\VT Work\2021-2022 Junior Year\2022 Spring\ECE 4424 Machine Learning\Project\yolov5\wandb\run-20220421_154155-3f232asn\logs\debug.log
2022-04-21 15:41:55,963 INFO    MainThread:18404 [wandb_init.py:_log_setup():439] Logging internal logs to C:\Users\alexa\Documents\VT Work\2021-2022 Junior Year\2022 Spring\ECE 4424 Machine Learning\Project\yolov5\wandb\run-20220421_154155-3f232asn\logs\debug-internal.log
2022-04-21 15:41:55,963 INFO    MainThread:18404 [wandb_init.py:init():472] calling init triggers
2022-04-21 15:41:55,963 INFO    MainThread:18404 [wandb_init.py:init():475] wandb.init called with sweep_config: {}
config: {'weights': 'yolov5s.pt', 'cfg': '', 'data': '../archive/custom.yaml', 'hyp': {'lr0': 0.01, 'lrf': 0.01, 'momentum': 0.937, 'weight_decay': 0.0005, 'warmup_epochs': 3.0, 'warmup_momentum': 0.8, 'warmup_bias_lr': 0.1, 'box': 0.05, 'cls': 0.5, 'cls_pw': 1.0, 'obj': 1.0, 'obj_pw': 1.0, 'iou_t': 0.2, 'anchor_t': 4.0, 'fl_gamma': 0.0, 'hsv_h': 0.015, 'hsv_s': 0.7, 'hsv_v': 0.4, 'degrees': 0.0, 'translate': 0.1, 'scale': 0.5, 'shear': 0.0, 'perspective': 0.0, 'flipud': 0.0, 'fliplr': 0.5, 'mosaic': 1.0, 'mixup': 0.0, 'copy_paste': 0.0}, 'epochs': 100, 'batch_size': 16, 'imgsz': 640, 'rect': False, 'resume': False, 'nosave': False, 'noval': False, 'noautoanchor': False, 'evolve': None, 'bucket': '', 'cache': None, 'image_weights': False, 'device': '', 'multi_scale': False, 'single_cls': False, 'optimizer': 'SGD', 'sync_bn': False, 'workers': 1, 'project': 'runs\\train', 'name': 'exp', 'exist_ok': False, 'quad': False, 'cos_lr': False, 'label_smoothing': 0.0, 'patience': 100, 'freeze': [0], 'save_period': -1, 'local_rank': -1, 'entity': None, 'upload_dataset': False, 'bbox_interval': -1, 'artifact_alias': 'latest', 'save_dir': 'runs\\train\\exp5'}
2022-04-21 15:41:55,963 INFO    MainThread:18404 [wandb_init.py:init():525] starting backend
2022-04-21 15:41:55,963 INFO    MainThread:18404 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=spawn, using: spawn
2022-04-21 15:41:55,968 INFO    MainThread:18404 [backend.py:ensure_launched():219] starting backend process...
2022-04-21 15:41:56,078 INFO    MainThread:18404 [backend.py:ensure_launched():224] started backend process with pid: 22588
2022-04-21 15:41:56,080 INFO    MainThread:18404 [wandb_init.py:init():534] backend started and connected
2022-04-21 15:41:56,083 INFO    MainThread:18404 [wandb_init.py:init():598] updated telemetry
2022-04-21 15:41:56,224 INFO    MainThread:18404 [wandb_init.py:init():629] communicating run to backend with 30 second timeout
2022-04-21 15:42:26,241 INFO    MainThread:18404 [interface_shared.py:_communicate_run():325] couldn't get run from backend
2022-04-21 15:42:26,242 ERROR   MainThread:18404 [wandb_init.py:init():634] backend process timed out
2022-04-21 15:42:26,242 ERROR   MainThread:18404 [wandb_init.py:init():645] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2022-04-21 16:15:19,020 INFO    MainThread:18404 [wandb_init.py:teardown():286] tearing down wandb.init
